global:
  smtp_smarthost: 'smtp.exmail.qq.com:587' 
  smtp_from: 'it-service@transwarp.io'
  smtp_auth_username: 'it-service@transwarp.io'
  smtp_auth_password: 'VnPnwe9^&7@3'
  smtp_require_tls: true
  wechat_api_url: 'https://qyapi.weixin.qq.com/cgi-bin/'
  wechat_api_secret: '8j0EeYfkJjEGQHuHTHVUHgeXiPeAPMSSXlH4hlMI66o'
  wechat_api_corp_id: 'ww42078e41a647ec9d'
templates:
  - './template/wechat.tmpl'

route:
  group_by: ['alertname']
  group_wait: 10s #首次警报触发10秒后发送邮件
  group_interval: 30s #发送新的警报前等待30秒
  repeat_interval: 1h #重复发送警报邮件的周期，注意，间隔太短会引起邮件轰炸
  receiver: 'web.hook.prometheusalert'
  routes:
  - match:
      severity: critical
    repeat_interval: 10m
    receiver: wechat

receivers:
- name: 'email'
  email_configs:
  - to: 'all-it@transwarp.io'
    headers: { Subject: "[!!!WARNING!!!] Prometheus报警邮件" }
- name: 'wechat'
  wechat_configs:
  - send_resolved: false
    corp_id: 'ww42078e41a647ec9d'
    to_user: 'xinchen.luan|yi.feng|lvqinglong-80628'
#    to_party: '16'
    message: '{{ template "wechat.default.message" . }}'
    agent_id: '1000008'
    api_secret: '8j0EeYfkJjEGQHuHTHVUHgeXiPeAPMSSXlH4hlMI66o'
- name: 'web.hook.prometheusalert'
  webhook_configs:
  - url: 'http://localhost:8080/prometheus/alert'
